name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and Push the Docker image
        env:
          DASHBOARD_ENV: ${{ secrets.DASHBOARD_ENV }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo $DASHBOARD_ENV | base64 -d > ./.env
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          docker build -t $DOCKER_HUB_USER/philsa-dashboard:latest .
          docker push $DOCKER_HUB_USER/philsa-dashboard:latest
